name: variables and secrets
env:
  WF_VAR: "workFlow level variable"
on:
  push:
jobs:

  test_variables:
    if: (github.event_name == 'pull_request')
    env: 
      JOB_VAR: "Job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Steps level variable"
        run: |
          echo ${{github.actor}}
          echo $GITHUB_JOB
          echo $JOB_VAR
          echo $WF_VAR
          echo $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
